export const BRAID_TYPES = [
  "Box Braids",
  "Knotless Braids",
  "Goddess Braids",
  "Tranças Nagô",
  "Tranças Embutidas",
  "Tranças Raiz",
  "Tranças Feed-in",
  "Tranças Jumbo",
  "Micro Braids",
  "Tranças Twist",
  "Senegalese Twist",
  "Havana Twist",
  "Marley Twist",
  "Crochet Braids",
  "Faux Locs",
  "Soft Locs",
  "Butterfly Locs",
  "Boho Braids",
  "Fulani Braids",
  "Tribal Braids",
  "Lemonade Braids",
  "Stitch Braids",
  "Cornrows",
  "Tranças com Linha",
  "Tranças com Kanekalon",
  "Tranças com Jumbo Hair",
  "Tranças Coloridas",
  "Tranças com Apliques",
  "Tranças Infantis",
  "Tranças Masculinas",
  "Tranças para Alongamento",
  "Tranças Decoradas",
  "Tranças com Miçangas",
  "Tranças com Acessórios"
];
